'''
Authors
  - C. Selmi: written in 2021
'''

mirror_conf = '20170430'
optical_conf = '20150730'

simulated = None

BASE_PATH = None
CONFIGURATION_ROOT_FOLDER = None
CALIBRATION_ROOT_FOLDER = None
OPT_DATA_FOLDER = None
OUT_FOLDER = None
MIRROR_FOLDER = None
OPTICAL_FOLDER = None

OPD_IMAGES_ROOT_FOLDER = None
PHASECAM_ROOT_FOLDER = None
LOG_ROOT_FOLDER = None
IFFUNCTIONS_ROOT_FOLDER = None
FLAT_ROOT_FOLD = None
CALIBRATION_ROOT_FOLDER = None
ALIGNMENT_ROOT_FOLDER = None
ZERNIKECOMMANDTEST_ROOT_FOLDER = None
NOISE_ROOT_FOLDER = None
SPL_ROOT_FOLDER = None
CALIBALL_ROOT_FOLDER = None
MODESVECTOR_ROOT_FOLDER = None
MODALBASE_ROOT_FOLDER = None
MODALAMPLITUDE_ROOT_FOLDER = None
COMMANDHISTORY_ROOT_FOLDER = None
GEOTRANSFORM_ROOT_FOLDER = None
ROT_OPT_ALIGN_ROOT_FOLDER = None
PT_ROOT_FOLDER = None
OPD_SERIES_ROOT_FOLDER = None
REPEATABILITY_ROOT_FOLDER = None
PISTON_TEST_ROOT_FOLDER = None
MAPPING_TEST_ROOT_FOLDER = None
ACC_ROOT_FOLDER = None
