#base_path: 'D:/M4/'
base_path: '/home/runner/work/M4/M4/test/data'
simulated_interf: True
simulated_dm: True
simulated_accelerometers: True
simulated_angleRotator: True
simulated_m4Exapode: True
simulated_dp: True
simulated_parSlider: True
simulated_par: True
simulated_rmSlider: True
simulated_rm: True
simulated_tempSensors: True

#simulated: 1
